version: "3"

services:
  george:
    build:
      context: .
      args:
        PG_USERNAME: "${PG_USERNAME}"
        PG_DATABASE: "${PG_DATABASE}"
        PG_PASSWORD: "${PG_PASSWORD}"
        SESSION_SECRET: "${SESSION_SECRET}"
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    command: sh -c "node server/index.js"

  postgres:
    restart: always
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "${PG_USERNAME}"
      POSTGRES_DB: "${PG_DATABASE}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data/"

  redis:
    image: "bitnami/redis:latest"
    command: redis-server --protected-mode no
    environment:
      - REDIS_APPENDFSYNC=always
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/var/lib/redis"
      - "redis.conf:/usr/local/etc/redis/redis.conf"

volumes:
  pgdata: null
  redis-data: null
  redis.conf: null
