name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: Borales/actions-yarn@v2.0.1
      - name: install
        with:
          cmd: install
      - uses: Borales/actions-yarn@v2.0.1
      - name: build
        with:
          cmd: build
        env:
          CI: true
