name: Node CI

on: [push]

jobs:
  build:
    name: yarn install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: marcelovicentegc/actions-yarn@v2.1.0
        with:
          cmd: install
      - uses: marcelovicentegc/actions-yarn@v2.1.0
        with:
          cmd: build
        env:
          CI: true
